version: '1'
services:
  backend:
    container_name: api_typescript
    build: ./
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: npm run dev
    volumes:
      - ./:/app-backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      # Os dados abaixo se referem ao container `db`
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=dbname
      - DB_HOST=database
      - DB_PORT=3306
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001'] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5

  database:
    image: mysql:8.0.21
    container_name: database
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # Senha do banco de dados
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost'] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
